
CREATE TABLE IF NOT EXISTS _metaVersion (
	currentVersion VARCHAR(8) NOT NULL PRIMARY KEY,
	isLocked BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO _metaVersion VALUES ('0');

CREATE TABLE IF NOT EXISTS _metaChange (
	metaChangeId INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	dateApplied TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE INDEX `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO _metaChange (name) VALUES ('_metaVersion.isLocked');
